apiVersion: apps/v1
kind: Deployment
metadata:
  name: goober-frontend
  namespace: goober
spec:
  replicas: 2
  selector:
    matchLabels:
      app: goober-frontend
  template:
    metadata:
      labels:
        app: goober-frontend
    spec:
      containers:
        - name: frontend
          image: goober-frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: goober-frontend
  namespace: goober
spec:
  selector:
    app: goober-frontend
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP